// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4I9eLDbOYxWfTtjWD6JrMymeTy7UQm0',
    appId: '1:722879115497:android:b9fdfa6dd7c6b50dc1c078',
    messagingSenderId: '722879115497',
    projectId: 'weteam-1968a',
    databaseURL: 'https://weteam-1968a-default-rtdb.firebaseio.com',
    storageBucket: 'weteam-1968a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc10UyJz6B9Zr9qEgH7gnCjbVa6b3GGcY',
    appId: '1:722879115497:ios:eec41a4031fd4357c1c078',
    messagingSenderId: '722879115497',
    projectId: 'weteam-1968a',
    databaseURL: 'https://weteam-1968a-default-rtdb.firebaseio.com',
    storageBucket: 'weteam-1968a.appspot.com',
    androidClientId: '722879115497-184l0a3d4o0asprqv49rr5917t4hvcfg.apps.googleusercontent.com',
    iosClientId: '722879115497-snpbls5g403v2nig98b4sbi64ub3u2eh.apps.googleusercontent.com',
    iosBundleId: 'com.login.frontWeteam',
  );
}
