// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmXbjZ8rgHbXDNhMw50RrzB4qBkEN5Ak',
    appId: '1:722879115497:web:fc77c18c32ff5847c1c078',
    messagingSenderId: '722879115497',
    projectId: 'weteam-1968a',
    authDomain: 'weteam-1968a.firebaseapp.com',
    databaseURL: 'https://weteam-1968a-default-rtdb.firebaseio.com',
    storageBucket: 'weteam-1968a.appspot.com',
    measurementId: 'G-R0DY4T1C37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4I9eLDbOYxWfTtjWD6JrMymeTy7UQm0',
    appId: '1:722879115497:android:568c66ada86b4fb2c1c078',
    messagingSenderId: '722879115497',
    projectId: 'weteam-1968a',
    databaseURL: 'https://weteam-1968a-default-rtdb.firebaseio.com',
    storageBucket: 'weteam-1968a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc10UyJz6B9Zr9qEgH7gnCjbVa6b3GGcY',
    appId: '1:722879115497:ios:a60737dff2e659fcc1c078',
    messagingSenderId: '722879115497',
    projectId: 'weteam-1968a',
    databaseURL: 'https://weteam-1968a-default-rtdb.firebaseio.com',
    storageBucket: 'weteam-1968a.appspot.com',
    androidClientId: '722879115497-23h6sich43q38hadja766mjmh2fo33et.apps.googleusercontent.com',
    iosClientId: '722879115497-pn4plqtkckc7eshge430bavfp7t6gc3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontWeteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc10UyJz6B9Zr9qEgH7gnCjbVa6b3GGcY',
    appId: '1:722879115497:ios:d68fd3d593f2b00cc1c078',
    messagingSenderId: '722879115497',
    projectId: 'weteam-1968a',
    databaseURL: 'https://weteam-1968a-default-rtdb.firebaseio.com',
    storageBucket: 'weteam-1968a.appspot.com',
    androidClientId: '722879115497-23h6sich43q38hadja766mjmh2fo33et.apps.googleusercontent.com',
    iosClientId: '722879115497-4trl6hm7gp0itqrbbo3b45eu3830rhnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontWeteam.RunnerTests',
  );
}
